services:
  app:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    container_name: ${APPNAME}_app
    profiles:
      - full
      - maho
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - .env
    volumes:
      - ./src:/app
      - ./Caddyfile:/etc/frankenphp/Caddyfile
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - maho-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # Rimosso depends_on rigido per permettere l'avvio flessibile con i profili

  db:
    #image: mariadb:lts
    image: yobasystems/alpine-mariadb:latest
    container_name: ${APPNAME}_db
    profiles:
      - full
      - database
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/conf.d/maho.cnf
    networks:
      - maho-network

  redis:
    image: redis:7-alpine
    container_name: ${APPNAME}_redis
    profiles:
      - full
      - redis
    restart: unless-stopped
    command: [ "redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru", "--save", "900 1", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - maho-network

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: ${APPNAME}_phpmyadmin
    restart: unless-stopped
    profiles:
      - phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "8080:80"
    networks:
      - maho-network

networks:
  maho-network:
    driver: bridge

volumes:
  db_data:
  redis_data:
  caddy_data:
  caddy_config:
